### ISSUE TITLE
loss computation in distributed training

### ISSUE THREAD

**Issue by subash-khanal** [naver-ai/pcmepp#1] opened 2023-09-09 17:09 UTC
Thanks for releasing the code for your amazing work!

I was trying to play with PCME/PCME++ a little bit. I have some confusion regarding the loss computation in distributed training. Specifically in [this line](https://github.com/naver-ai/pcmepp/blob/a09596c6a2f5868db25783e7cc22cf1e6f458483/pcmepp/engine.py#L185), should not the loss be computed with embeddings gathered from all devices? Currently it looks like the embeddings from one modality (image) from only current rank device are being used to compute loss with gathered embeddings from all devices for another modality (caption). Could you help me if I am misunderstanding something here?

**Comment by SanghyukChun** [comment] 2023-09-11 05:12
Hello, it looks like you have already resolved the issue. 
To be clear, the below instructions are executed by **each GPU device**.

```python
loss_img, loss_dict_img = self.criterion(img_emb, {'mean': cap_emb_all}, distributed=True)
loss_cap, loss_dict_cap = self.criterion(cap_emb, {'mean': img_emb_all}, distributed=True)
```

These instructions are the same as the purple cells (if we think each `cell` is the mini-batch samples corresponding to **each GPU**) in the below figure (from [my paper](https://sanghyukchun.github.io/home/media/papers/chun2023pcmepp.pdf)):

<img width="400" alt="image" src="https://github.com/naver-ai/pcmepp/assets/4919315/4b7f2f4d-67cd-45a8-b0c4-d17818136594">

At the end of the loss computing, all losses are summed to compute the final loss, therefore it is the same as computing losses for every cell (every mini-batch)

Note that it is only for InfoNCE (i.e., batch-wise contrastive loss), while my implementation (e.g., PCME or PCME++) based on **pair-wise** contrastive loss needs a different solution.

**Comment by SanghyukChun** [comment] 2023-09-24 07:55
Close the issue as it looks like the issue is resolved. Please re-open the issue if necessary.

**Closed as completed by SanghyukChun** 2023-09-24 07:55 UTC
